/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package complaints;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import static javax.swing.JOptionPane.YES_OPTION;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mukesh
 */
public class system_incharge extends javax.swing.JFrame {

    /**
     * Creates new form system_incharge
     */
    String usernameGlobal;
    
    public system_incharge() {
        initComponents();
    }
    
    public system_incharge(String user) {
        initComponents();
        usernameGlobal=user;
        nameLbl.setText("          Welcome, "+usernameGlobal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        nameLbl = new javax.swing.JLabel();
        signout_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        civil_cntLbl = new javax.swing.JLabel();
        ele_cntLbl = new javax.swing.JLabel();
        net_cntLbl = new javax.swing.JLabel();
        gen_cntLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        civilwk_cntLbl = new javax.swing.JLabel();
        elewk_cntLbl = new javax.swing.JLabel();
        netwk_cntLbl = new javax.swing.JLabel();
        genwk_cntLbl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        typeCB = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        hostelCB = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        redressedCB = new javax.swing.JRadioButton();
        unredressedCB = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        recordTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        date_CB = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        start_dateTxt = new javax.swing.JTextField();
        end_dateTxt = new javax.swing.JTextField();
        view_Btn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        floorTxt = new javax.swing.JTextField();
        floor_CB = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        nameLbl.setBackground(new java.awt.Color(33, 75, 140));
        nameLbl.setFont(new java.awt.Font("Lato Heavy", 0, 18)); // NOI18N
        nameLbl.setForeground(new java.awt.Color(255, 255, 255));
        nameLbl.setBorder(null);
        nameLbl.setOpaque(true);

        signout_btn.setBackground(new java.awt.Color(204, 16, 22));
        signout_btn.setFont(new java.awt.Font("Lato Heavy", 0, 18)); // NOI18N
        signout_btn.setForeground(new java.awt.Color(255, 255, 255));
        signout_btn.setText("Sign Out");
        signout_btn.setBorder(null);
        signout_btn.setBorderPainted(false);
        signout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signout_btnActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Private complaints"));
        jPanel1.setToolTipText("");
        jPanel1.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(201, 1, 1));
        jLabel1.setText("Waiting Redressal");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("ELECTRICAL");
        jLabel2.setBorder(null);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("CIVIL");
        jLabel3.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("NETWORK");
        jLabel4.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("GENERAL");
        jLabel5.setBorder(null);

        civil_cntLbl.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        civil_cntLbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        civil_cntLbl.setText("0");

        ele_cntLbl.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        ele_cntLbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        ele_cntLbl.setText("0");

        net_cntLbl.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        net_cntLbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        net_cntLbl.setText("0");

        gen_cntLbl.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        gen_cntLbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        gen_cntLbl.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(civil_cntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ele_cntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(net_cntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gen_cntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addGap(21, 21, 21)))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(civil_cntLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ele_cntLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(net_cntLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(gen_cntLbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Private complaints"));
        jPanel2.setToolTipText("");
        jPanel2.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(201, 1, 1));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("<html>\n<center>\nAll complaints<br>registered this week\n</center>");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setText("ELECTRICAL");
        jLabel7.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel8.setText("CIVIL");
        jLabel8.setBorder(null);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel9.setText("NETWORK");
        jLabel9.setBorder(null);

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel10.setText("GENERAL");
        jLabel10.setBorder(null);

        civilwk_cntLbl.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        civilwk_cntLbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        civilwk_cntLbl.setText("0");

        elewk_cntLbl.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        elewk_cntLbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        elewk_cntLbl.setText("0");

        netwk_cntLbl.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        netwk_cntLbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        netwk_cntLbl.setText("0");

        genwk_cntLbl.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        genwk_cntLbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        genwk_cntLbl.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(civilwk_cntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(elewk_cntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(netwk_cntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genwk_cntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(civilwk_cntLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(elewk_cntLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(netwk_cntLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(genwk_cntLbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel11.setText("FILTER PRIVATE COMPLAINTS");

        jLabel12.setText("Type : ");

        typeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ANY", "CIVIL", "ELECTRICAL", "NETWORK", "GENERAL" }));

        jLabel13.setText("Hostel :");

        hostelCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ANY", "ASHOKA", "ASHWATHA BOYS WING", "ASHWATHA GIRLS WING" }));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Status"));

        buttonGroup1.add(redressedCB);
        redressedCB.setText("Redressed");

        buttonGroup1.add(unredressedCB);
        unredressedCB.setSelected(true);
        unredressedCB.setText("Unredressed");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(redressedCB)
                .addGap(40, 40, 40)
                .addComponent(unredressedCB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redressedCB)
                    .addComponent(unredressedCB))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        recordTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "Roll No.", "Room No.", "Hostel", "description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(recordTable);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Date of Complaint"));

        date_CB.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        date_CB.setSelected(true);
        date_CB.setText("All time");
        date_CB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_CBActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel15.setText("Start date :");

        jLabel16.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel16.setText("End date :");

        start_dateTxt.setEnabled(false);

        end_dateTxt.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(end_dateTxt)
                    .addComponent(start_dateTxt))
                .addGap(12, 12, 12))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date_CB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(start_dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(end_dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        view_Btn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        view_Btn.setText("View RECORDS");
        view_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_BtnActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Floor"));

        jLabel14.setText("Floor :");

        floorTxt.setText("ALL");
        floorTxt.setEnabled(false);

        floor_CB.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        floor_CB.setSelected(true);
        floor_CB.setText("All floors");
        floor_CB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        floor_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor_CBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(32, 32, 32)
                        .addComponent(floorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(floor_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(floor_CB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(floorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 1143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(signout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(32, 32, 32)
                                .addComponent(typeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(42, 42, 42)
                                .addComponent(hostelCB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(view_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel12)
                                            .addComponent(typeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13)
                                            .addComponent(hostelCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18)
                                .addComponent(view_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signout_btnActionPerformed
        int choice=JOptionPane.showConfirmDialog(this, "Do you really want to SIGN OUT ?","USER LOGOUT",YES_NO_OPTION);
        if(choice==YES_OPTION)
        {
            this.setVisible(false);
            new login().setVisible(true);
        }
    }//GEN-LAST:event_signout_btnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //Summarise the pending private complaints
        try
        {
            Class.forName("java.sql.DriverManager");
            
            String host="localhost";
            String port="3306";
            String dbname="COMPLAINTS";
            String username="complaints";
            String password="iiitdm123";
            
            String dburl="jdbc:mysql://"+host+":"+port+"/"+dbname;
            
            Connection con = (Connection) DriverManager.getConnection(dburl, username,password);
            Statement stmt = (Statement) con.createStatement();
            
            String comp_dept;
            int count;
            
            //get unredressed complaints from private_complaints
            String query="Select type, count(*) CNT from private_complaints where status!='REDRESSED' group by type";
            
            ResultSet rs=stmt.executeQuery(query);
            
            while(rs.next())
            {
                comp_dept=rs.getString("type");
                count=rs.getInt("CNT");
                
                if(comp_dept.equals("CIVIL"))
                {
                    civil_cntLbl.setText(""+count);
                    if(count>10)
                        civil_cntLbl.setForeground(Color.red);
                }
                
                else if(comp_dept.equals("ELECTRICAL"))
                {
                    ele_cntLbl.setText(""+count);
                    if(count>10)
                        ele_cntLbl.setForeground(Color.red);
                }
                
                else if(comp_dept.equals("NETWORK"))
                {
                    net_cntLbl.setText(""+count);
                    if(count>10)
                        net_cntLbl.setForeground(Color.red);
                }
                
                else if(comp_dept.equals("GENERAL"))
                {
                    gen_cntLbl.setText(""+count);
                    if(count>10)
                        gen_cntLbl.setForeground(Color.red);
                }
            }
            
            rs.close();
            
            //All private complaints  registered this week
            query="Select type, count(*) CNT from private_complaints where (YEAR(CURRENT_DATE)-YEAR(create_date))<=1 and WEEK(CURRENT_DATE,2)=WEEK(create_date,2) group by type";
           
            ResultSet rs_week=stmt.executeQuery(query);
            while(rs_week.next())
            {
                comp_dept=rs_week.getString("type");
                count=rs_week.getInt("CNT");
                
                if(comp_dept.equals("CIVIL"))
                {
                    civilwk_cntLbl.setText(""+count);
                    if(count>10)
                        civilwk_cntLbl.setForeground(Color.red);
                }
                
                else if(comp_dept.equals("ELECTRICAL"))
                {
                    elewk_cntLbl.setText(""+count);
                    if(count>10)
                        elewk_cntLbl.setForeground(Color.red);
                }
                
                else if(comp_dept.equals("NETWORK"))
                {
                    netwk_cntLbl.setText(""+count);
                    if(count>10)
                        netwk_cntLbl.setForeground(Color.red);
                }
                
                else if(comp_dept.equals("GENERAL"))
                {
                    genwk_cntLbl.setText(""+count);
                    if(count>10)
                        genwk_cntLbl.setForeground(Color.red);
                }
            }
            
            rs_week.close();
            
            
            stmt.close();
            con.close();
            
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void date_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_CBActionPerformed
        // TODO add your handling code here:
        if(date_CB.isSelected()==false)
        {
            start_dateTxt.setEnabled(true);
            end_dateTxt.setEnabled(true);
        }
        
        else
        {
            start_dateTxt.setEnabled(false);
            end_dateTxt.setEnabled(false);
        }
    }//GEN-LAST:event_date_CBActionPerformed

    private void view_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_BtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel rec_model=(DefaultTableModel) recordTable.getModel();
        
        int rowCount = rec_model.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            rec_model.removeRow(i);
}

        try
        {
            Class.forName("java.sql.DriverManager");
            
            String host="localhost";
            String port="3306";
            String dbname="COMPLAINTS";
            String username="complaints";
            String password="iiitdm123";
            
            String dburl="jdbc:mysql://"+host+":"+port+"/"+dbname;
            
            Connection con = (Connection) DriverManager.getConnection(dburl, username,password);
            Statement stmt = (Statement) con.createStatement();
            
            String base_query="SELECT type, roll_no, c_roomno, c_hostel, description from private_complaints where";
            
            String parameters="";
            
            String type=(String) typeCB.getSelectedItem();
            if(type.equals("ANY"))
                type="%";
            parameters=parameters.concat("(type like '"+type+"')");
            
            String hostel=(String) hostelCB.getSelectedItem();
            if(hostel.equals("ANY"))
                hostel="%";
            parameters=parameters.concat(" and (c_hostel like '"+hostel+"')");
            
            if(date_CB.isSelected()==false)
            {
                String start_date=start_dateTxt.getText();
                String end_date=end_dateTxt.getText();
                
                parameters=parameters.concat(" and (create_date between '"+start_date+"' and '"+end_date+"')");
            }
            
            if(redressedCB.isSelected()==true)
                parameters=parameters.concat(" and status='REDRESSED'");
            
            else if(unredressedCB.isSelected()==true)
                parameters=parameters.concat(" and status!='REDRESSED'");
                
            
            if(floor_CB.isSelected()==false)
            {
                int floor=Integer.parseInt(floorTxt.getText());
                parameters=parameters.concat(" and TRUNCATE(c_roomno/100,0)-1="+floor);
            }
            
            String query=base_query+" "+parameters;
            ResultSet rs=stmt.executeQuery(query);
            
            String rs_type,rs_rollno,rs_hostel,rs_description;
            int rs_roomno;
            
            while(rs.next())
            {
                rs_type=rs.getString("type");
                rs_rollno=rs.getString("roll_no");
                rs_roomno=rs.getInt("c_roomno");
                rs_hostel=rs.getString("c_hostel");
                rs_description=rs.getString("description");
                
                rec_model.addRow(new Object[] {rs_type,rs_rollno,rs_roomno,rs_hostel,rs_description});
            }
            
            rs.close();
            stmt.close();
            con.close();
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_view_BtnActionPerformed

    private void floor_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor_CBActionPerformed
        // TODO add your handling code here:
        if(floor_CB.isSelected()==false)
            floorTxt.setEnabled(true);
        
        else
            floorTxt.setEnabled(false);
    }//GEN-LAST:event_floor_CBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(system_incharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(system_incharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(system_incharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(system_incharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new system_incharge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel civil_cntLbl;
    private javax.swing.JLabel civilwk_cntLbl;
    private javax.swing.JCheckBox date_CB;
    private javax.swing.JLabel ele_cntLbl;
    private javax.swing.JLabel elewk_cntLbl;
    private javax.swing.JTextField end_dateTxt;
    private javax.swing.JTextField floorTxt;
    private javax.swing.JCheckBox floor_CB;
    private javax.swing.JLabel gen_cntLbl;
    private javax.swing.JLabel genwk_cntLbl;
    private javax.swing.JComboBox<String> hostelCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel net_cntLbl;
    private javax.swing.JLabel netwk_cntLbl;
    private javax.swing.JTable recordTable;
    private javax.swing.JRadioButton redressedCB;
    private javax.swing.JButton signout_btn;
    private javax.swing.JTextField start_dateTxt;
    private javax.swing.JComboBox<String> typeCB;
    private javax.swing.JRadioButton unredressedCB;
    private javax.swing.JButton view_Btn;
    // End of variables declaration//GEN-END:variables
}
